baseURL = "http://bhoot.sh/"
languageCode = "en-us"
title = "Site under construction"

# Theme to use
theme = "simple-hugo-theme"

# Copyright
copyright = "© 2019 — Jayesh Bhoot — All rights reserved."

# Pagination
paginate = 10 
paginatePath = "page"

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# Menu
[menu]
  # Header
  [[menu.main]]
    url = "/blog/"
    name = "blog"
    weight = 1
  [[menu.main]]
    url = "/about/"
    name = "about"
    weight = 2
  [[menu.main]]
    url = "/contact/"
    name = "contact"
    weight = 3

  # Footer
  [[menu.footer]]
    url = "https://github.com/jayesh-bhoot"
    name = "GitHub"
    weight = 1
  [[menu.footer]]
    url = "/blog/index.xml"
    name = "RSS"
    weight = 2
  [[menu.footer]]
    url = "mailto:jayesh@bhoot.sh"
    name = "Email me"
    weight = 3

[params]
# default: Jan 2, 2006
datefmt  = "02 Jan 2006"
